// Generated by CoffeeScript 1.9.1
(function() {
  var browserify, concat, gulp;

  gulp = require("gulp");

  browserify = require("gulp-browserify");

  concat = require("gulp-concat");

  gulp.task("browserify", function() {
    return gulp.src("src/js/main.js").pipe(browserify({
      transform: "reactify"
    })).pipe(concat("main.js")).pipe(gulp.dest("dist/js"));
  });

  gulp.task("copy", function() {
    return gulp.src("src/index.html").pipe(gulp.dest("./dist"));
  });

  gulp.task("default", ["browserify", "copy"]);

  gulp.task("w", function() {
    gulp.watch("src/**/*.js", ["browserify"]);
    return gulp.watch("src/**/*.html", ["copy"]);
  });

}).call(this);
