// Generated by CoffeeScript 1.9.1
(function() {
  var APP, React;

  APP = require("./components/app");

  React = require("react");

  React.render(<APP />, document.getElementById("main"));

}).call(this);
