// Generated by CoffeeScript 1.9.1
(function() {
  var AppActions, AppConstants, AppDispatcher;

  AppConstants = require("../constants/app-constants.js");

  AppDispatcher = require("../dispatchers/app-dispatcher.js");

  AppActions = {
    addItem: function(item) {
      return AppDispatcher.handleViewAction({
        actionType: AppConstants.ADD_ITEM,
        item: item
      });
    },
    removeItem: function(index) {
      return AppDispatcher.handleViewAction({
        actionType: AppConstants.REMOVE_ITEM,
        index: index
      });
    },
    decreaseItem: function(index) {
      return AppDispatcher.handleViewAction({
        actionType: AppConstants.DECREASE_ITEM,
        index: index
      });
    },
    increaseItem: function(index) {
      return AppDispatcher.handleViewAction({
        actionType: AppConstants.INCREASE_ITEM,
        index: index
      });
    }
  };

  module.exports = AppActions;

}).call(this);
