// Generated by CoffeeScript 1.9.1
(function() {
  var AddToCart, AppStore, Catalog, React, getCatalog;

  React = require("react");

  AppStore = require("../sotore/app-store.js");

  AddToCart = require("../components/app-addtocart.js");

  getCatalog = function() {
    return {
      items: AppStore.prototype.getCatalog()
    };
  };

  Catalog = React.createClass({
    getInitialState: function() {
      return getCatalog();
    },
    render: function() {
      var items;
      items = this.state.items.map(function(item, i) {
        return (
          <tr>
              <td>{item.title}</td>
              <td>${item.cost}</td>
              <td><AddToCart item={item} /></td>
          </tr>
      );
      });
      return (
      <table className="table table-hover">
          {items}
      </table>
    );
    }
  });

  module.exports = Catalog;

}).call(this);
