// Generated by CoffeeScript 1.9.1
(function() {
  var AppStore, Cart, Decrease, Increase, React, RemoveFromCart, cartItems;

  React = require("react");

  AppStore = require("../sotore/app-store.js");

  RemoveFromCart = require("../components/app-removefromcart.js");

  Increase = require("../components/app-increase.js");

  Decrease = require("../components/app-decrease.js");

  cartItems = function() {
    return {
      items: AppStore.prototype.getCart()
    };
  };

  Cart = React.createClass({
    getInitialState: function() {
      return cartItems();
    },
    componentWillMount: function() {
      AppStore.prototype.addChangeListener(this._onChange);
      return setTimeout((function(_this) {
        return function() {
          return _this.setState(cartItems());
        };
      })(this), 1000);
    },
    _onChange: function() {
      return this.setState(cartItems());
    },
    render: function() {
      var items, total;
      total = 0;
      items = this.state.items.map(function(item, i) {
        var subtotal;
        subtotal = item.cost * item.qty;
        total += subtotal;
        return (
          <tr key={i}>
              <td><RemoveFromCart index={i} /></td>
              <td>{item.title}</td>
              <td>{item.qty}</td>
              <td>
                <Increase index={i} />
                <Decrease index={i} />
              </td>
              <td>${subtotal}</td>
          </tr>
      );
      });
      return (
        <table className="table table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Item</th>
                <th>Qty</th>
                <th></th>
                <th>Subtotal</th>
              </tr>
            </thead>
            <tbody>
              {items}
            </tbody>
            <tfoot>
              <tr>
                <td colSpan="4" className="text-right">Total</td>
                <td>${total}</td>
              </tr>
            </tfoot>
        </table>
    );
    }
  });

  module.exports = Cart;

}).call(this);
